"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"
import { useAuth } from "./auth-context"

export type LanguageCode = "en" | "hi" | "mr" | "ta" | "te" | "kn" | "bn"

export interface LanguageOption {
  code: LanguageCode
  name: string
  flag: string
}

export const languages: LanguageOption[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "hi", name: "Hindi", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", flag: "🇮🇳" },
  { code: "te", name: "Telugu", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", flag: "🇮🇳" },
]

// Translation dictionaries for each language
const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // English is the default language, so we use the keys as values
    dashboard: "Dashboard",
    expenses: "Expenses",
    goals: "Goals",
    challenges: "Challenges",
    settings: "Settings",
    finbot: "FinBot",
    emotion_insights: "Emotion Insights",
    welcome: "Welcome",
    track_finances: "Track your finances and manage your budget",
    income: "Income",
    expenses_label: "Expenses",
    balance: "Balance",
    overview: "Overview",
    charts: "Charts",
    recent: "Recent Expenses",
    accounts: "Accounts",
    expense_breakdown: "Expense Breakdown",
    spending_by_category: "Your spending by category",
    budget_status: "Budget Status",
    financial_status: "Your current financial status",
    quick_actions: "Quick Actions",
    view_all_expenses: "View All Expenses",
    manage_goals: "Manage Goals",
    daily_expenses: "Daily Expenses",
    spending_over_days: "Your spending over the last 30 days",
    monthly_breakdown: "Monthly Breakdown",
    expenses_by_category: "Expenses by category this month",
    category_distribution: "Category Distribution",
    percentage_by_category: "Percentage of spending by category",
    budget_vs_actual: "Budget vs Actual",
    spending_compares: "How your spending compares to your budget",
    recent_expenses: "Recent Expenses",
    latest_transactions: "Your latest transactions",
    update_income: "Update Income",
    scan_receipt: "Scan Receipt",
    add_expense: "Add Expense",
    logout: "Logout",
    profile: "Profile",
    appearance: "Appearance",
    dark_mode: "Dark Mode",
    language: "Language",
    reset_data: "Reset All Data",
    save: "Save",
    cancel: "Cancel",
    amount: "Amount",
    date: "Date",
    category: "Category",
    description: "Description",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    success: "Success",
    error: "Error",
    loading: "Loading",
    no_data: "No data available",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    total: "Total",
    average: "Average",
    minimum: "Minimum",
    maximum: "Maximum",
    today: "Today",
    yesterday: "Yesterday",
    this_week: "This Week",
    last_week: "Last Week",
    this_month: "This Month",
    last_month: "Last Month",
    this_year: "This Year",
    last_year: "Last Year",
    custom_range: "Custom Range",
    apply: "Apply",
    reset: "Reset",
    close: "Close",
    open: "Open",
    next: "Next",
    previous: "Previous",
    first: "First",
    last: "Last",
    page: "Page",
    of: "of",
    items_per_page: "Items per page",
    showing: "Showing",
    to: "to",
    entries: "entries",
    all: "All",
    none: "None",
    select_all: "Select All",
    select_none: "Select None",
    select: "Select",
    selected: "Selected",
    clear: "Clear",
    clear_all: "Clear All",
    clear_selection: "Clear Selection",
    emotion_tracking: "Emotion Tracking",
    how_you_feel: "How do you feel about your finances today?",
    emotion_history: "Emotion History",
    emotion_insights_title: "Emotion Insights",
    emotion_insights_description: "Track your financial emotions and gain insights",
    happy: "Happy",
    sad: "Sad",
    anxious: "Anxious",
    confident: "Confident",
    confused: "Confused",
    stressed: "Stressed",
    excited: "Excited",
    neutral: "Neutral",
    // Add more translations as needed
  },
  hi: {
    dashboard: "डैशबोर्ड",
    expenses: "खर्च",
    goals: "लक्ष्य",
    challenges: "चुनौतियां",
    settings: "सेटिंग्स",
    finbot: "फिनबॉट",
    emotion_insights: "भावनात्मक अंतर्दृष्टि",
    welcome: "स्वागत है",
    track_finances: "अपने वित्त को ट्रैक करें और अपना बजट प्रबंधित करें",
    income: "आय",
    expenses_label: "खर्च",
    balance: "शेष राशि",
    overview: "अवलोकन",
    charts: "चार्ट",
    recent: "हाल के खर्च",
    accounts: "खाते",
    expense_breakdown: "खर्च का विश्लेषण",
    spending_by_category: "श्रेणी के अनुसार आपका खर्च",
    budget_status: "बजट स्थिति",
    financial_status: "आपकी वित्तीय स्थिति",
    quick_actions: "त्वरित कार्रवाई",
    view_all_expenses: "सभी खर्च देखें",
    manage_goals: "लक्ष्य प्रबंधित करें",
    daily_expenses: "दैनिक खर्च",
    spending_over_days: "पिछले 30 दिनों में आपका खर्च",
    monthly_breakdown: "मासिक विश्लेषण",
    expenses_by_category: "इस महीने श्रेणी के अनुसार खर्च",
    category_distribution: "श्रेणी वितरण",
    percentage_by_category: "श्रेणी के अनुसार खर्च का प्रतिशत",
    budget_vs_actual: "बजट बनाम वास्तविक",
    spending_compares: "आपका खर्च आपके बजट से कैसे तुलना करता है",
    recent_expenses: "हाल के खर्च",
    latest_transactions: "आपके नवीनतम लेनदेन",
    update_income: "आय अपडेट करें",
    scan_receipt: "रसीद स्कैन करें",
    add_expense: "खर्च जोड़ें",
    logout: "लॉगआउट",
    profile: "प्रोफ़ाइल",
    appearance: "उपस्थिति",
    dark_mode: "डार्क मोड",
    language: "भाषा",
    reset_data: "सभी डेटा रीसेट करें",
    save: "सहेजें",
    cancel: "रद्द करें",
    amount: "राशि",
    date: "तारीख",
    category: "श्रेणी",
    description: "विवरण",
    add: "जोड़ें",
    edit: "संपादित करें",
    delete: "हटाएं",
    confirm: "पुष्टि करें",
    success: "सफलता",
    error: "त्रुटि",
    loading: "लोड हो रहा है",
    no_data: "कोई डेटा उपलब्ध नहीं है",
    search: "खोज",
    filter: "फ़िल्टर",
    sort: "क्रमबद्ध करें",
    ascending: "आरोही",
    descending: "अवरोही",
    total: "कुल",
    average: "औसत",
    minimum: "न्यूनतम",
    maximum: "अधिकतम",
    today: "आज",
    yesterday: "कल",
    this_week: "इस सप्ताह",
    last_week: "पिछले सप्ताह",
    this_month: "इस महीने",
    last_month: "पिछले महीने",
    this_year: "इस साल",
    last_year: "पिछले साल",
    custom_range: "कस्टम रेंज",
    apply: "लागू करें",
    reset: "रीसेट करें",
    close: "बंद करें",
    open: "खोलें",
    next: "अगला",
    previous: "पिछला",
    first: "पहला",
    last: "अंतिम",
    page: "पेज",
    of: "का",
    items_per_page: "प्रति पेज आइटम",
    showing: "दिखा रहा है",
    to: "से",
    entries: "प्रविष्टियां",
    all: "सभी",
    none: "कोई नहीं",
    select_all: "सभी का चयन करें",
    select_none: "किसी का चयन न करें",
    select: "चयन करें",
    selected: "चयनित",
    clear: "साफ़ करें",
    clear_all: "सभी साफ़ करें",
    clear_selection: "चयन साफ़ करें",
    emotion_tracking: "भावना ट्रैकिंग",
    how_you_feel: "आज आप अपने वित्त के बारे में कैसा महसूस करते हैं?",
    emotion_history: "भावना इतिहास",
    emotion_insights_title: "भावनात्मक अंतर्दृष्टि",
    emotion_insights_description: "अपनी वित्तीय भावनाओं को ट्रैक करें और अंतर्दृष्टि प्राप्त करें",
    happy: "खुश",
    sad: "दुखी",
    anxious: "चिंतित",
    confident: "आत्मविश्वासी",
    confused: "भ्रमित",
    stressed: "तनावग्रस्त",
    excited: "उत्साहित",
    neutral: "तटस्थ",
    // Add more translations as needed
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    expenses: "खर्च",
    goals: "उद्दिष्टे",
    challenges: "आव्हाने",
    settings: "सेटिंग्ज",
    finbot: "फिनबॉट",
    emotion_insights: "भावनिक अंतर्दृष्टी",
    welcome: "स्वागत आहे",
    track_finances: "आपले वित्त ट्रॅक करा आणि आपले बजेट व्यवस्थापित करा",
    income: "उत्पन्न",
    expenses_label: "खर्च",
    balance: "शिल्लक",
    overview: "आढावा",
    charts: "चार्ट",
    recent: "अलीकडील खर्च",
    accounts: "खाती",
    expense_breakdown: "खर्चाचे विश्लेषण",
    spending_by_category: "श्रेणीनुसार तुमचा खर्च",
    budget_status: "बजेट स्थिती",
    financial_status: "तुमची आर्थिक स्थिती",
    quick_actions: "त्वरित क्रिया",
    view_all_expenses: "सर्व खर्च पहा",
    manage_goals: "उद्दिष्टे व्यवस्थापित करा",
    daily_expenses: "दैनिक खर्च",
    spending_over_days: "गेल्या 30 दिवसांत तुमचा खर्च",
    monthly_breakdown: "मासिक विश्लेषण",
    expenses_by_category: "या महिन्यात श्रेणीनुसार खर्च",
    category_distribution: "श्रेणी वितरण",
    percentage_by_category: "श्रेणीनुसार खर्चाची टक्केवारी",
    budget_vs_actual: "बजेट विरुद्ध प्रत्यक्ष",
    spending_compares: "तुमचा खर्च तुमच्या बजेटशी कसा तुलना करतो",
    recent_expenses: "अलीकडील खर्च",
    latest_transactions: "तुमचे नवीनतम व्यवहार",
    update_income: "उत्पन्न अपडेट करा",
    scan_receipt: "पावती स्कॅन करा",
    add_expense: "खर्च जोडा",
    logout: "लॉगआउट",
    profile: "प्रोफाइल",
    appearance: "दिसणे",
    dark_mode: "डार्क मोड",
    language: "भाषा",
    reset_data: "सर्व डेटा रीसेट करा",
    save: "जतन करा",
    cancel: "रद्द करा",
    amount: "रक्कम",
    date: "तारीख",
    category: "श्रेणी",
    description: "वर्णन",
    add: "जोडा",
    edit: "संपादित करा",
    delete: "हटवा",
    confirm: "पुष्टी करा",
    success: "यश",
    error: "त्रुटी",
    loading: "लोड होत आहे",
    no_data: "कोणताही डेटा उपलब्ध नाही",
    search: "शोध",
    filter: "फिल्टर",
    sort: "क्रमवारी लावा",
    ascending: "चढत्या क्रमाने",
    descending: "उतरत्या क्रमाने",
    total: "एकूण",
    average: "सरासरी",
    minimum: "किमान",
    maximum: "कमाल",
    today: "आज",
    yesterday: "काल",
    this_week: "या आठवड्यात",
    last_week: "गेल्या आठवड्यात",
    this_month: "या महिन्यात",
    last_month: "गेल्या महिन्यात",
    this_year: "या वर्षी",
    last_year: "गेल्या वर्षी",
    custom_range: "सानुकूल श्रेणी",
    apply: "लागू करा",
    reset: "रीसेट करा",
    close: "बंद करा",
    open: "उघडा",
    next: "पुढील",
    previous: "मागील",
    first: "पहिले",
    last: "शेवटचे",
    page: "पृष्ठ",
    of: "पैकी",
    items_per_page: "प्रति पृष्ठ आयटम",
    showing: "दर्शवत आहे",
    to: "ते",
    entries: "नोंदी",
    all: "सर्व",
    none: "काहीही नाही",
    select_all: "सर्व निवडा",
    select_none: "काहीही निवडू नका",
    select: "निवडा",
    selected: "निवडलेले",
    clear: "साफ करा",
    clear_all: "सर्व साफ करा",
    clear_selection: "निवड साफ करा",
    emotion_tracking: "भावना ट्रॅकिंग",
    how_you_feel: "आज तुम्हाला तुमच्या वित्ताबद्दल कसे वाटते?",
    emotion_history: "भावना इतिहास",
    emotion_insights_title: "भावनिक अंतर्दृष्टी",
    emotion_insights_description: "तुमच्या आर्थिक भावना ट्रॅक करा आणि अंतर्दृष्टी मिळवा",
    happy: "आनंदी",
    sad: "दुःखी",
    anxious: "चिंताग्रस्त",
    confident: "आत्मविश्वासी",
    confused: "गोंधळलेले",
    stressed: "तणावग्रस्त",
    excited: "उत्साहित",
    neutral: "तटस्थ",
    // Add more translations as needed
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    expenses: "செலவுகள்",
    goals: "இலக்குகள்",
    challenges: "சவால்கள்",
    settings: "அமைப்புகள்",
    finbot: "ஃபின்போட்",
    emotion_insights: "உணர்ச்சி நுண்ணறிவுகள்",
    welcome: "வரவேற்கிறோம்",
    track_finances: "உங்கள் நிதியைக் கண்காணித்து உங்கள் பட்ஜெட்டை நிர்வகிக்கவும்",
    income: "வருமானம்",
    expenses_label: "செலவுகள்",
    balance: "இருப்பு",
    overview: "கண்ணோட்டம்",
    charts: "விளக்கப்படங்கள்",
    recent: "சமீபத்திய செலவுகள்",
    accounts: "கணக்குகள்",
    // Add more translations as needed
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    expenses: "ఖర్చులు",
    goals: "లక్ష్యాలు",
    challenges: "సవాళ్లు",
    settings: "సెట్టింగ్‌లు",
    finbot: "ఫిన్‌బాట్",
    emotion_insights: "భావోద్వేగ అంతర్దృష్టులు",
    welcome: "స్వాగతం",
    track_finances: "మీ ఆర్థిక స్థితిని ట్రాక్ చేయండి మరియు మీ బడ్జెట్‌ను నిర్వహించండి",
    income: "ఆదాయం",
    expenses_label: "ఖర్చులు",
    balance: "బ్యాలెన్స్",
    overview: "అవలోకనం",
    charts: "చార్ట్‌లు",
    recent: "ఇటీవలి ఖర్చులు",
    accounts: "ఖాతాలు",
    // Add more translations as needed
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    expenses: "ವೆಚ್ಚಗಳು",
    goals: "ಗುರಿಗಳು",
    challenges: "ಸವಾಲುಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    finbot: "ಫಿನ್‌ಬಾಟ್",
    emotion_insights: "ಭಾವನಾತ್ಮಕ ಒಳನೋಟಗಳು",
    welcome: "ಸ್ವಾಗತ",
    track_finances: "ನಿಮ್ಮ ಹಣಕಾಸನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಬಜೆಟ್ ನಿರ್ವಹಿಸಿ",
    income: "ಆದಾಯ",
    expenses_label: "ವೆಚ್ಚಗಳು",
    balance: "ಬ್ಯಾಲೆನ್ಸ್",
    overview: "ಅವಲೋಕನ",
    charts: "ಚಾರ್ಟ್‌ಗಳು",
    recent: "ಇತ್ತೀಚಿನ ವೆಚ್ಚಗಳು",
    accounts: "ಖಾತೆಗಳು",
    // Add more translations as needed
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    expenses: "খরচ",
    goals: "লক্ষ্য",
    challenges: "চ্যালেঞ্জ",
    settings: "সেটিংস",
    finbot: "ফিনবট",
    emotion_insights: "আবেগ অন্তর্দৃষ্টি",
    welcome: "স্বাগতম",
    track_finances: "আপনার অর্থ ট্র্যাক করুন এবং আপনার বাজেট পরিচালনা করুন",
    income: "আয়",
    expenses_label: "খরচ",
    balance: "ব্যালেন্স",
    overview: "ওভারভিউ",
    charts: "চার্ট",
    recent: "সাম্প্রতিক খরচ",
    accounts: "অ্যাকাউন্ট",
    // Add more translations as needed
  },
}

interface LanguageContextType {
  currentLanguage: LanguageOption
  setLanguage: (language: LanguageOption) => void
  translate: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { user, updateUser } = useAuth()
  const [currentLanguage, setCurrentLanguage] = useState<LanguageOption>(languages[0])

  useEffect(() => {
    // Set language based on user preference
    if (user?.language) {
      const userLanguage = languages.find((lang) => lang.code === user.language)
      if (userLanguage) {
        setCurrentLanguage(userLanguage)
      }
    }
  }, [user])

  const setLanguage = (language: LanguageOption) => {
    setCurrentLanguage(language)
    if (user) {
      updateUser({ language: language.code })
    }
  }

  const translate = (key: string): string => {
    const langDict = translations[currentLanguage.code]
    return langDict[key] || key
  }

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, translate }}>{children}</LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export const useTranslation = useLanguage
